### ISSUE TITLE
Get user from FirebaseFirestore

### ISSUE THREAD

**Issue by hadrienm** [flyerhq/flutter_firebase_chat_core#100]
Hello,

I try to get specific user, and for that I create user_service but when I try to get a user I have this error:

- Unhandled Exception: type 'Timestamp' is not a subtype of type 'int?' in type cast

The line affected by the error is the following:

- createdAt: json['createdAt'] as int?,

My code is the follow : 

```
  Future<types.User?> readUser() async {
    final User? user = _firebaseAuth.currentUser;
    final DocumentReference<Map<String, dynamic>> docUser =
        FirebaseFirestore.instance.collection('users').doc(user!.uid);
    final DocumentSnapshot<Map<String, dynamic>> snapshot = await docUser.get();

    if (snapshot.exists) {
      return types.User.fromJson(snapshot.data()!);
    }
    return null;
  }
```
thanks for your help,

**Comment by demchenkoalex** [comment]
Hi! AFAIR firebase stores dates in some firebase's format, and you need to modify it to milliseconds (int) before using `User.fromJson`. Similarly to this line https://github.com/flyerhq/flutter_firebase_chat_core/blob/main/lib/src/util.dart#L114
