### ISSUE TITLE
How to create room for a specific user without using ```FirebaseChatCore.instance.users()``` and ```StreamBuilder()```

### ISSUE THREAD

**Issue by infinite-dev22** [flyerhq/flutter_firebase_chat_core#119]
Hello 👋, I want a user to be able to send a message to another user through my using your library... I have the user UID from firebase which i use to create a user but i can't fetch that specific user so i can create a room for them chat.

```
void _handlePressed(UserProfile userProfile, BuildContext context) async {
    final navigator = Navigator.of(context);

    await FirebaseChatCore.instance.createUserInFirestore(
        types.User(
            firstName: userProfile.name,
            id: userProfile.userId, // UID from Firebase Authentication
            imageUrl: userProfile.profilePicture,
            lastName: '',
        ),
    );

    // I tried this, raises an error.
    types.User otherUser = (
    FirebaseChatCore.instance.users().where(
        (event) => event.where(
            (element) => element.id == userProfile.userId).isNotEmpty));

    final room = await FirebaseChatCore.instance.createRoom(otherUser);

    navigator.pop();
    await navigator.push(
        CupertinoPageRoute(
            builder: (context) => ChatPage(
                room: room,
            ),
        ),
    );
}
```

**Comment by demchenkoalex** [comment]
Hey! But here

```dart
await FirebaseChatCore.instance.createUserInFirestore(
  types.User(
    firstName: userProfile.name,
    id: userProfile.userId, // UID from Firebase Authentication
    imageUrl: userProfile.profilePicture,
    lastName: '',
  ),
);
```

you already have your user? you just created it to call `createUserInFirestore`. So you can use the same  in `createRoom`?

**Comment by infinite-dev22** [comment]
Hey, thanks for reply to my question.
How do i use the same user in ```createRoom```. I am failing to get the created user so I can pass it to ```createRoom``` as my <h4>MRE</h4> above showed.

**Comment by infinite-dev22** [comment]
My use case is... I am using this library in my app to add a chat feature, My app provides a user with user profiles from which the user can take a look and optionally start a chat with a desired one. So the user taps a button and if the chat user doesn't already exist one is created and if the room doesn't already exist one is created for a chat between the currently authenticated user and the other user selected.
I managed to figure out how a chat user is created but have failed to get that created chat user into the ```createRoom``` method.

**Comment by superaldo** [comment]
for create a room:
```dart
final room = await FirebaseChatCore.instance.createRoom(
      otherUser: otherUser,
      metadata: {'endProcess': false}, //optional
    );

await navigator.push(
      MaterialPageRoute(
        builder: (context) => ChatPage(
          room: room,
        ),
      ),
    );
```

**Comment by demchenkoalex** [comment]
> My app provides a user with user profiles from which the user can take a look and optionally start a chat with a desired one

So you already have a list of users then? Just take one from the list and use it to call `createRoom` as presented above.

> How do i use the same user in createRoom.

You have this
```dart
await FirebaseChatCore.instance.createUserInFirestore(
  types.User(
    firstName: userProfile.name,
    id: userProfile.userId, // UID from Firebase Authentication
    imageUrl: userProfile.profilePicture,
    lastName: '',
  ),
);
```
Why not just create a user separately
```
final otherUser = types.User(
  firstName: userProfile.name,
  id: userProfile.userId, // UID from Firebase Authentication
  imageUrl: userProfile.profilePicture,
  lastName: '',
),
await FirebaseChatCore.instance.createUserInFirestore(otherUser)
final room = await FirebaseChatCore.instance.createRoom(otherUser);
```

**Comment by infinite-dev22** [comment]
Brilliant... thanks for this, Sir. solves it perfectly
