### ISSUE TITLE
Upgrade to cloud_firestore: ^2.0.0

### ISSUE THREAD

**Issue by petoknm** [flyerhq/flutter_firebase_chat_core#13]
Is there a plan to upgrade `cloud_firestore`? I would like to use some of the newer features in my app.

Thank you :)

**Comment by demchenkoalex** [comment]
Hi @petoknm sorry didn't know there is a new version :) right now we are focused on https://github.com/flyerhq/flutter_chat_ui/issues/24 but I'll try to see if there are any breaking changes and how much time this update will take

**Comment by jangruenwaldt** [comment]
Doesnt take long at all I think? I did that upgrade myself and Im not even sure if anything had to be changed...

**Comment by demchenkoalex** [comment]
Still iOS, Android and web needs to be checked and verified, but yeah, can probably be done tomorrow

**Comment by demchenkoalex** [comment]
Hi, sorry for the delay, released in [v1.0.3](https://github.com/flyerhq/flutter_firebase_chat_core/releases/tag/v1.0.3)
