### ISSUE TITLE
Firebase Core got a major upgrade to 3.0.0 from 2.x.x, we now have a conflict issue.

### ISSUE THREAD

**Issue by MonkeyDrone** [flyerhq/flutter_firebase_chat_core#130]
Because flutter_firebase_chat_core 1.6.7 depends on firebase_core ^2.13.0 and no versions of flutter_firebase_chat_core match >1.6.7 <2.0.0, flutter_firebase_chat_core ^1.6.7 requires firebase_core ^2.13.0.
So, because 'xyzproject' depends on both firebase_core ^3.0.0 and flutter_firebase_chat_core ^1.6.7, version solving failed.

**Comment by kubawich** [comment]
Bump

**Comment by demchenkoalex** [comment]
on it

**Comment by demchenkoalex** [comment]
released here [v1.6.8](https://github.com/flyerhq/flutter_firebase_chat_core/releases/tag/v1.6.8)
