### ISSUE TITLE
FirebaseChatCore.instance.createRoom(chatUser); return imageUrl, name, and metadata null

### ISSUE THREAD

**Issue by superdiazzz** [flyerhq/flutter_firebase_chat_core#135]
# General

## What bug do you experience? 🐞
I already have a users collection in Firestore with a slightly different schema and more additional fields. Then I instantiated the types.User version in the library and did createRoom. The document was successfully created but I found several important fields were empty. As an example, I attached a screenshot.

## How can it be reproduced? 🤔
A few steps to define where does the bug occur.
Step 1. i Installed 1.6.8 flutter_firebase_chat_core
Step 2. in my UserRepository i call this function,
```
Future<types.Room> createRoomFromCustomUser(UserModel user) async {
    final chatUser = user.toChatUser();
    print(chatUser.toJson());
    return await FirebaseChatCore.instance.createRoom(chatUser);
  }
```
UserModel is my user model that I have in firestore `users`. The printout of the Json contains something like this: 
`{firstName: Gundumin, id: DzsLTeibcBWriWr1SidvcyImG5i1, imageUrl: https://firebasestorage.googleapis.com/v0/b/xxxx.firebasestorage.app/o/users%2FDzsLTeibcBWriWr1SidvcyImG5i1.jpg?alt=media&token=6d681d01-0bd5-4b08-ab50-ae8f6298f9f3, metadata: {email: admin@xxx.id}}`

json values are exists, but after i called `createRoom` in my collection room values like imageUrl, name, and metadata will be null

## What behavior is expected? 💡
I expected those fields exists on the rooms Document collection

<br />

# Extras

## Screenshots or videos 📸
Attached on file
<img width="794" alt="Screenshot 2024-12-10 at 10 03 58" src="https://github.com/user-attachments/assets/be8c8d93-dc5f-46c0-bfc9-29d0935dec52">

## Code snippets 📝
This is root cause, previous code are okay

```
Future<types.Room> createRoomFromCustomUser(UserModel user) async {
    final chatUser = user.toChatUser();
    print(chatUser.toJson());
    return await FirebaseChatCore.instance.createRoom(chatUser);
  }
```

toChatUser extension

```
extension UserMapper on UserModel {
  types.User toChatUser() {
    return types.User(
      id: id,
      firstName: name,
      imageUrl: photo,
      metadata: {
        'email' : email
      }
    );
  }
}
```

<br />

# Environment info

I use

flutter:  3.22.1
  flutter_firebase_chat_core: ^1.6.8

`flutter doctor -v` output 👇

```sh
```

<br />

# Platform

Android Pixel 3a, Android 14.0 UpsidedownCake (Emulator on Android Studio)

<br />

# Additional context

nothing
<!-- Thank you for making us better 🤝--!>

*UPDATE*
After I explored further, why was the following field intentionally made null?
<img width="581" alt="Screenshot 2024-12-10 at 13 30 01" src="https://github.com/user-attachments/assets/e7054a6a-6db1-43a7-be83-4b0fd8caa2d1">

**Comment by demchenkoalex** [comment]
hey! I will soon remove this package, please don't use it :) core of the package is a couple of calls to Firebase functions, so it can be easily created for your specific use case

**Comment by superdiazzz** [comment]
@demchenkoalex  Hi bro I have temporary solution now, i use metaData to keep my properties. 

What do you mean by removing this package?. You going to remove this whole library ([flutter_firebase_chat_core](https://github.com/flyerhq/flutter_firebase_chat_core))? Too bad, i have use it with my small project. However my feature chat intentionally not for long conversation just for asking the question and people answering it and some messages and done. Chat is over, my Cron Service will cleaning up the history. Please do not remove this library, perhaps one day i will make PR to fix some parts.

**Comment by demchenkoalex** [comment]
yes, this will be an example instead. I will focus solely on better UI (I recently released v2 alpha). This package at its core is super small it will take you 20 minutes to write it from scratch and you won't have to compromise. I will make a guide instead, a good starting point where people will be able to write something like this very quickly and then expand based on their needs.
