### ISSUE TITLE
How to get last message?

### ISSUE THREAD

**Issue by islam-diab** [flyerhq/flutter_firebase_chat_core#137]
I need to get last message and show it under name of user

![Screenshot_1735063420](https://github.com/user-attachments/assets/9567e3c0-edd6-4715-8ba7-b14d884f9d57)

**Comment by demchenkoalex** [comment]
hey! this package will be deprecated soon, please don't use it :) you will have to come up with a solution yourself in this case

**Comment by islam-diab** [comment]
Ok, Thanks for the clarification.
