### ISSUE TITLE
Sort Rooms stream by last updated

### ISSUE THREAD

**Issue by mashegoindustries** [flyerhq/flutter_firebase_chat_core#18]

**Comment by mashegoindustries** [comment]
Hi,

I am streaming rooms with code below
FirebaseChatCore.instance.rooms()

I would like to show a room with the most recent activity at the top.

Is there a work around to sort rooms based on activity/last updated

**Comment by demchenkoalex** [comment]
Hi @mashegoindustries, please see this release [v1.1.1](https://github.com/flyerhq/flutter_firebase_chat_core/releases/tag/v1.1.1) (specifically find a documentation comment I am referring to, it should give you the idea)
