### ISSUE TITLE
New messages on chat's notifications

### ISSUE THREAD

**Issue by SalahAdDin** [flyerhq/flutter_firebase_chat_core#19]
## Is your feature request related to a problem?
In every chat application, there is the need to be informed when a new unreaded message come in a chat, so she/he can be aware he/she must read the new messages.

## What solution would you suggest?
Related to the `fireabase_chat_core`, following the events on the stream and having a **delivered/unread** status, it is possible to warn when a new message comes with a notification.

## Extras
**Screenshots or videos 📸**
If applicable, add screenshots or videos to help explain your feature.

**Code snippets 📝**
If applicable, add code samples to help explain your feature.

```dart
// Your snippet here...
```

## Related issues/PRs
Let us know if this is related to any issue/pull request.

**Comment by demchenkoalex** [comment]
Hi @SalahAdDin what do you mean by notification? From the description it sound to me more like you are describing a banner inside the chat which says "Unread messages" or something

**Comment by markzakharyan** [comment]
There definitely should be a way to add a message as 'read'. I think there should be a function that can be invoked when the user reaches the bottom of the chat (similar to the function that already exists for when the user reaches the top of the chat)

**Comment by SalahAdDin** [comment]
> Hi @SalahAdDin what do you mean by notification? From the description it sound to me more like you are describing a banner inside the chat which says "Unread messages" or something

When you are not using the app and a new message come, a notification message comes to your cellphone, at least on whatsapp and others.

**Comment by demchenkoalex** [comment]
@SalahAdDin it is out of scope of this package. Notifications setup is always in the native code and you have tons of providers, this is a package and not the application :) you need to choose your provider and create a Cloud Function which will send a notification when new message comes in.

**Comment by demchenkoalex** [comment]
@markzakharyan this is out of topic of this discussion, see #9

**Comment by demchenkoalex** [comment]
Closing because notifications can't be implemented inside the package, or at least I am unaware of how it possibly could be done without locking to specific provider.

**Comment by SalahAdDin** [comment]
> Closing because notifications can't be implemented inside the package, or at least I am unaware of how it possibly could be done without locking to specific provider.

You could provide a documentation about **CloudFunctions** integration with this package since this is the **Firebase Backend** integration package. 

What do you think?

**Comment by demchenkoalex** [comment]
@SalahAdDin

1) Cloud Functions are in the paid plan
2) Cloud Functions are more backend related and we are talking Flutter here (I'm a mobile developer)
3) The purpose of this package is to give you a head start, working MVP version or at least a direction, not to create a fully blown solution
4) We are open to PRs, you can research this and update the docs
