### ISSUE TITLE
When using orderByUpdatedAt, no messages get returned

### ISSUE THREAD

**Issue by markzakharyan** [flyerhq/flutter_firebase_chat_core#24]
# General

## What bug do you experience? 🐞

When using `orderByUpdatedAt: true`, no messages get returned

## How can it be reproduced? 🤔

set `orderByUpdatedAt` to be true inside rooms stream. I'm using a group chat, and updatedAt is configured in firestore for all rooms.

## What behavior is expected? 💡
Rooms list is sorted by how lately they were updated
<br />

# Extras

## Screenshots or videos 📸

Relevant Database Snippet:
![image](https://user-images.githubusercontent.com/56100600/126055026-2fb89ce2-b072-4cfb-8178-d8cc6966c234.png)

Without `orderByUpdatedAt`:
![image](https://user-images.githubusercontent.com/56100600/126055046-f4d9bc30-b22b-4ec0-ae7c-280af4a5f6d4.png)

With `orderByUpdatedAt`:
![image](https://user-images.githubusercontent.com/56100600/126055051-8f4263e0-a5cc-4a6a-814d-076a597d12c1.png)

## Code snippets 📝
If applicable, add code samples to help explain your problem.

```dart
stream: FirebaseChatCore.instance.rooms(orderByUpdatedAt: true),
```

<br />

# Environment info

Please specify the flutter, flutter_firebase_chat_core versions.

flutter: 2.2.1 stable
flutter_firebase_chat_core: ^1.1.2

`flutter doctor -v` output 👇

```sh
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.1083], locale en-US)
    • Flutter version 2.2.1 at C:\Users\space\Documents\flutter
    • Framework revision 02c026b03c (7 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\space\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.58.1)
    • VS Code at C:\Users\space\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.106
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.48

• No issues found!
```

<br />

# Platform

Pixel 4 XL Android Emulator

Android 11 (API 30)

<br />

<!-- Thank you for making us better 🤝--!>

**Comment by demchenkoalex** [comment]
Hi @markzakharyan did you follow the documentation comment for that property? Did you create an index?

**Comment by markzakharyan** [comment]
@demchenkoalex Oops! This is on me, I didn't configure my index properly. Thank you
