### ISSUE TITLE
Add metadata to message

### ISSUE THREAD

**Issue by stanleykoz** [flyerhq/flutter_firebase_chat_core#26]
Hi, is there any way to add metadata to message and then send it? From what I found out it is not impossible. So I assume it can only be done with cloud function but can someone explain where do I call this function to provide full info about the message (message id and so on)

**Comment by demchenkoalex** [comment]
Hi @stanleykoz! What's your use case? Messages are created by you before you send them and they have a metadata field available

**Comment by stanleykoz** [comment]
That's what I thought but as far as I am concerned they are created using PartialText which has only text property. I tried just after sending the message updating it with metadata but no result. Basically my problem is to set any other property of the message (except text because it happens out od the box)

**Comment by demchenkoalex** [comment]
okay, that's might be something I have missed, so I will need to take a second look at this, metadata should probably be available

**Comment by stanleykoz** [comment]
Please let me know if you find something out :)

**Comment by stanleykoz** [comment]
And did you find any solution for that?

**Comment by demchenkoalex** [comment]
@stanleykoz I have a full-time job and other contributors are on vacations, please be patient :)

**Comment by demchenkoalex** [comment]
Released in [v1.1.4](https://github.com/flyerhq/flutter_firebase_chat_core/releases/tag/v1.1.4). Sorry for the waiting!
