### ISSUE TITLE
Don't create room if user not send message to other user

### ISSUE THREAD

**Issue by MindMayhem** [flyerhq/flutter_firebase_chat_core#28]
Hi, is it possible with this package to make this feature in a subject? In my app, users can open a dialogue with each other, but I don't want the room to be created if the person doesn't typed anything

**Comment by demchenkoalex** [comment]
Just create a room when you need to? It is a function **you call**, so do whatever is best for your use case. When you `sendMessage` just check if your room exists and `createRoom` if needed.

**Comment by demchenkoalex** [comment]
Closing this one, feel free to re-open if you think the solution I described doesn't work.
