### ISSUE TITLE
Message Type not set in 1.3.0

### ISSUE THREAD

**Issue by eopeter** [flyerhq/flutter_firebase_chat_core#32]
In the recent update, when you send a message, the "type" property is not set in the Firebase entity. Was working before the recent upgrade to 1.3.0

**Comment by eopeter** [comment]
Before Update:
![image](https://user-images.githubusercontent.com/2012979/131463127-852c3dc1-0111-4dd3-a852-4b0261b7d804.png)

After Update
![image](https://user-images.githubusercontent.com/2012979/131463215-b16e1b43-15f5-4d62-9534-845552595c33.png)

This causes fetching the message to bomb when trying to parse 'type' to String in flutter_chat_types/lib/src/message.dart

<img width="839" alt="image" src="https://user-images.githubusercontent.com/2012979/131463472-95c4b21d-1ee6-4891-8387-453fe9032b88.png">

**Comment by demchenkoalex** [comment]
Sorry about that, I missed that while doing migration to `json_serializable`. Should be fixed in [v1.3.1](https://github.com/flyerhq/flutter_firebase_chat_core/releases/tag/v1.3.1).

**Comment by eopeter** [comment]
Awesome works!!
