### ISSUE TITLE
Example does not compile

### ISSUE THREAD

**Issue by appdevingenio** [flyerhq/flutter_firebase_chat_core#34]
The example does not compile, lib/chat.dart has an issue line 84:

 lib/chat.dart:84:25: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
          final file = File(filePath);

Flutter environment:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.60.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by demchenkoalex** [comment]
Forgot to update dependencies, updated on `main` branch now :)
