### ISSUE TITLE
type Timestamp is not a subtype of type 'int?' in type cast

### ISSUE THREAD

**Issue by sharukhkhanajm** [flyerhq/flutter_firebase_chat_core#35]
Hi 
while parsing the user data from the Firestore I get this error "type 'Timestamp' is not a subtype of type 'int?' in type cast".
Here's how I am trying to get the user
```
//get the firestore user from the firestore collection
  Future<types.User> getFirestoreUser() {
    return _db
        .doc('/users/${firebaseUser.value!.uid}')
        .get()
        .then((documentSnapshot) {
      return types.User.fromJson(documentSnapshot.data()!);
    });
  }
```

Firestore collection
![image](https://user-images.githubusercontent.com/47321682/134275196-3cae811b-e818-4be8-abdf-987cd29e5edc.png)

I did some digging and found out that here is how you are saving the timestamp
![image](https://user-images.githubusercontent.com/47321682/134274965-8b8db378-6a93-4cfd-a251-98f7fe41dc27.png)

so I am not getting the fact that why are you having the **int** for the timestamp?

**Comment by demchenkoalex** [comment]
Hey @sharukhkhanajm these are internal Firebase types, which can't be used in `chat_ui` and other places, because we will be locked with Firebase as a dependency. That's why we have normal timestamp (int). If you'd look at the codebase for another minute you'd have found that to change Firebase internal timestamp to int, you can do this https://github.com/flyerhq/flutter_firebase_chat_core/blob/main/lib/src/firebase_chat_core.dart#L325

**Comment by sharukhkhanajm** [comment]
ohh yes thanks @demchenkoalex  i should have looked more.
thanks for your help 👍 

if anyone wondering this is how i have achieved it


```
//get the firestore user from the firestore collection
  Future<types.User> getFirestoreUser() {
    return _db
        .doc('/users/${firebaseUser.value!.uid}')
        .get()
        .then((documentSnapshot) {
      final data = documentSnapshot.data()!;
      data['createdAt'] = data['createdAt']?.millisecondsSinceEpoch;
      data['id'] = documentSnapshot.id;
      data['lastSeen'] = data['lastSeen']?.millisecondsSinceEpoch;
      data['updatedAt'] = data['updatedAt']?.millisecondsSinceEpoch;
      return types.User.fromJson(data);
    });
  }

```
