### ISSUE TITLE
Flutter web gives back a blank page

### ISSUE THREAD

**Issue by appdevingenio** [flyerhq/flutter_firebase_chat_core#36]
The doc on how to deploy to web is a bit unclear. I have built the project, deployed it in Firebase and when hitting the provided link, it opens a blank page (chrome and safari).

Here are the steps I followed:

1- Create web app in firebase and created as specified in the doc a firebase-config.js in the web directory with the output of the web project creation (without script tags).

2- flutter build web

3- firebase init providing as the location of the index file: build/web, selected also single page
firebase,json was created:
{
  "hosting": {
    "public": "build/web",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}

4- firebase deploy
I can see 36 files deployed, I hit the URL: https://flyerchat-c8d43.web.app/ and it just displays a white page

Output of flutter doctor:

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)

• No issues found!`

**Comment by demchenkoalex** [comment]
Hey @appdevingenio 

> The doc on how to deploy to web is a bit unclear.

What doc are you referring to? We don't have any deployment documentation. Example is working in development mode and it is not supposed to be deployed. Anything else is on developer's and Flutter side, creating project, adding Firebase dependencies, set up, building, deploying it, not the part of this package. I believe you will need to check out Flutter and https://firebase.flutter.dev documentation to find out how to deploy a project correctly.

**Comment by obrand69** [comment]
> Hey @appdevingenio
> 
> > The doc on how to deploy to web is a bit unclear.
> 
> What doc are you referring to? We don't have any deployment documentation. Example is working in development mode and it is not supposed to be deployed. Anything else is on developer's and Flutter side, creating project, adding Firebase dependencies, set up, building, deploying it, not the part of this package. I believe you will need to check out Flutter and https://firebase.flutter.dev documentation to find out how to deploy a project correctly.

I was a bit unclear. I have deployed Flutter web apps in the past in Firebase. Deployment works fine BUT the page that comes back is blank. There are instructions in the project for the config file, which I have also followed. Locally the config file did not work as expected throwing errors, I had to copy the code (firebase config) in the index file and I got the same exact result than deploying onto Firebase: a blank page.
So maybe the starting point is local deployment in dev mode which did not work following the instructions. I got the app to work fine on iOS with Firebase.
