### ISSUE TITLE
Null checked on a null

### ISSUE THREAD

**Issue by iisprey** [flyerhq/flutter_firebase_chat_core#37]
When I create a room, I got this error

```
Null check operator used on a null value
```

![Screenshot_select-area_20210925224205](https://user-images.githubusercontent.com/40313719/134784782-ffa80efd-ed64-48e2-938a-6ee0c7423711.jpg)

![Screenshot_select-area_20210925224231](https://user-images.githubusercontent.com/40313719/134784794-53d4fcaa-d5e0-433f-a920-4a1aee13ad28.jpg)

**Comment by iisprey** [comment]
I'm sorry that was my fault.
Sorry for the issue, package works great!

**Comment by BillieVijo** [comment]
sorry can you tell me how did you solve that

because i get the same error @iisprey

**Comment by Johnny-sel** [comment]
same issue
