### ISSUE TITLE
Efficiently get number of unread messages

### ISSUE THREAD

**Issue by thammaknot** [flyerhq/flutter_firebase_chat_core#41]
Hi, 

Thank you for creating this Flutter package. 

I'm trying to figure out how to efficiently get the number of unread messages (of a room) since the last time the user opened the room (so that I can show a notification bubble with a number in it). I looked through the API doc but didn't find anything that does that. It's possible that I missed it since I'm still learning this.

What's the best way to achieve this through the API?

Thanks in advance.

**Comment by demchenkoalex** [comment]
Hey @thammaknot I don't think we have that :( I'm not sure ATM how it would look like too.. again probably some Cloud Functions will be needed for this

**Comment by thammaknot** [comment]
Thanks for the reply.

**Comment by delegate-it** [comment]
Hi @thammaknot  did you manage to do this feature. I am interested in doing the same. It would be great to share it if you have find a solution.

**Comment by thammaknot** [comment]
Not really. We ended up using other solutions for Flutter chat (Matrix sdk) for other reasons.
