### ISSUE TITLE
Cache first when querying.

### ISSUE THREAD

**Issue by richard457** [flyerhq/flutter_firebase_chat_core#44]
Thank you for this great package, would love to first load data from cache then server, this would help in reducing cost on firestore side and good user experience, I thank you in advance.

**Comment by demchenkoalex** [comment]
Hey @richard457! 

You mean Firestore cache?

**Comment by richard457** [comment]
@demchenkoalex yes firestore cache.

**Comment by demchenkoalex** [comment]
So I think Firebase is using some cache underneath itself and everything above that - there was a very similar discussion in #45 you can read it there
