### ISSUE TITLE
where and how to create this file

### ISSUE THREAD

**Issue by rwema3** [flyerhq/flutter_firebase_chat_core#46]
<script>
  // Your web app's Firebase configuration
  var firebaseConfig = {
    apiKey: "...",
    authDomain: "[YOUR_PROJECT].firebaseapp.com",
    projectId: "[YOUR_PROJECT]",
    storageBucket: "[YOUR_PROJECT].appspot.com",
    messagingSenderId: "...",
    appId: "1:...:web:..."
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
</script>

**Comment by demchenkoalex** [comment]
Taken from here https://firebase.flutter.dev/docs/installation/web
