### ISSUE TITLE
Ability to choose Firebase project instead of default one

### ISSUE THREAD

**Issue by valas69** [flyerhq/flutter_firebase_chat_core#47]
I saw in the code that you use `Firestore.instance` and we can't change that. It's a bit problematic for apps using multiple firebase env
It would be nice to put an optional parameter to set the project

**Comment by demchenkoalex** [comment]
Hmm never thought about that. Do you have a hint how should I do it? instance is just a singleton pattern so users always use the same instance to avoid multiple subscriptions etc. I can pass firebase app ID somewhere?

**Comment by valas69** [comment]
Sure, here is the doc for FlutterFire for using the project we want
https://firebase.flutter.dev/docs/core/usage/#secondary-firebase-apps

You can maybe put an optional String parameter "app" in the singleton (I don't know if that is possible).
Here is a pseudo-code to do that:
`
if (app == null) {
  FirebaseFirestore.instance; // or FirebaseAuth.instance etc...
} else {
  FirebaseFirestore.instanceFor(app); // or FirebaseAuth.instanceFor(app) etc...
}
` 

or even set a method "setProject(String app)" that will set the project in the singleton.

I am asking this because some applications (like mine) use two different project.
The first one (default) is a production project and the second one is a dev project

**Comment by demchenkoalex** [comment]
I am deeply sorry for not implementing it right away and postponing it. Better late than never I guess. Released in [v1.5.2](https://github.com/flyerhq/flutter_firebase_chat_core/releases/tag/v1.5.2).
