### ISSUE TITLE
room.lastMessages returning empty list

### ISSUE THREAD

**Issue by TC3000** [flyerhq/flutter_firebase_chat_core#49]
I'm trying to get the last messages that was sent in a room using `room.lastMessages` but I'm always getting an empty list even when the room does have some messages in it, what am I missing?

Thanks for the awesome package btw.

**Comment by demchenkoalex** [comment]
Did you set up and tested the cloud function that will set them? It will not work out of the box

**Comment by TC3000** [comment]
Oh, I didn't, let me do that, thanks.

**Comment by AndroidDev-Rehan** [comment]
how to set up and test the cloud function that will set them? any guide

**Comment by demchenkoalex** [comment]
@AndroidDev-Rehan no guides, there are some basic examples in the docs, everything else is Firebase documentation and your code :)
