### ISSUE TITLE
Documentation regarding Firebase Storage security rules

### ISSUE THREAD

**Issue by sischnei** [flyerhq/flutter_firebase_chat_core#51]
Great project!! Would it be possible to add documentation regarding the firebase storage security rules - the example shows how to use Firebase Storage rules, but doesn't really provide any details on how to set up permissions.

**Comment by demchenkoalex** [comment]
Hey @sischnei [docs](https://docs.flyer.chat/flutter/firebase/firebase-rules) have comments on each line that describe precisely why they are written a specific way. To write additional rules, refer the Firebase documentation, it is not part of the chat, but Firebase itself. https://firebase.google.com/docs/rules

**Comment by sischnei** [comment]
I was not referring to the firebase firestore rules (database) but regarding firebase storage where e.g. photos are uploaded to. As the project offers tight integration with firebase, I think it would be nice to have a suggestion, how secure attachment storage can be implemented.

As an example, I find it difficult to see how you can allow uploading files (without allowing overwriting existing files) while at the same time preventing unauthorized access to attachments, thus only allowing users of a room to view the uploaded attachments. Maybe, it's easily done using the existing functions provided in the documentation, but then why not add a section regarding firebase storage security rules to the otherwise really helpful project documentation. :-)

**Comment by demchenkoalex** [comment]
Hey @sischnei as far as I recall there are 0 lines of code regarding firebase storage in the lib itself. Example folder serves 1 purpose - to give an example. This is not a production ready/secure/scalable project, just an example. So you can also say that I have no integration with firebase storage at all. I could use AWS storage or something as well. If something is missing in regard of library code that need to be added, I'd happily add it, but what you're asking is unfortunately outside of the scope of this particular lib.

**Comment by sischnei** [comment]
Ok - from that perspective I undestand. Thanks anyways!
