### ISSUE TITLE
Displaying Messages directly (creating room from backend)

### ISSUE THREAD

**Issue by NOaMTL** [flyerhq/flutter_firebase_chat_core#54]
Hello

I am trying to display the Chat ui (messages list) from a room.

I am creating room from a php backend, and also assigining users to the rooms from the same backend.

How do I display the Chat ui without having the room list ?

I noticed FirebaseChatCore.instance.room(String roomId) gives a Stream but how to get the object Room.

Thank you for your help

**Comment by demchenkoalex** [comment]
Hey @NOaMTL sorry for the late response, had health issues. Room is needed in this library to hold users inside, if you have your custom backend why use this package at all? I don't think this package will work good when part of logic is here and part is on the other backed. You can also fork and redo for your needs I guess.
