### ISSUE TITLE
Audio messages functionality missing.  Can I do PR?

### ISSUE THREAD

**Issue by GauravCalidig** [flyerhq/flutter_firebase_chat_core#55]
Hi, As i can seethe functionality to send audio is still missing, i have added a similar thing in my project, Just wanted to ask if i do a pull request for audio messages, will it be added?
I mean Are you guys looking for this feature?

**Comment by demchenkoalex** [comment]
Hey @GauravCalidig replied in the chat UI library, will close this one.
