### ISSUE TITLE
add user to a room

### ISSUE THREAD

**Issue by newengine** [flyerhq/flutter_firebase_chat_core#56]
how to add a new user to a room? thanks

**Comment by demchenkoalex** [comment]
I guess we need the update room method. You want to make a PR?

**Comment by newengine** [comment]
got it, thanks

**Comment by demchenkoalex** [comment]
Released in [v1.5.2](https://github.com/flyerhq/flutter_firebase_chat_core/releases/tag/v1.5.2).
