### ISSUE TITLE
How to filter users according to metadata

### ISSUE THREAD

**Issue by orangeRobot990** [flyerhq/flutter_firebase_chat_core#58]
Hello 👋 
So I added some information in the metada field. And in the users.dart example i changed the stream from the build to my stream function that filters.
I just noticed that the metadata from the current user and the actual user arent the same. Did i update the information incorrectly ? How could i filter the users according to metadata information

```
  final User? currentUser = FirebaseAuth.instance.currentUser;

  Stream<List<types.User>> filterUsers() async* {
    var users = FirebaseChatCore.instance.users();
    var filteredUser;
    await for (final doc in users) {
      for (final user in doc) {
        // check if user is different from us
        if (currentUser?.uid != user.id) {
          print(currentUser!.metadata.toString());
        }
      }
    }
  }
```
What I see in the metadata field is  : 
![image](https://user-images.githubusercontent.com/98290005/151468706-1da021b3-6894-41e9-9613-744397c7349e.png)

And how I updated the user's metadata

```
  void updateUserData() async {
    usersCollection
        .doc(currentUser!.uid.toString())
        .update({'metadata': activities});
  }
}
```
What I see in my firestore
![image](https://user-images.githubusercontent.com/98290005/151468862-1ae32c3f-d1e3-48e6-86b4-b11887c946c8.png)

**Comment by demchenkoalex** [comment]
`final User? currentUser = FirebaseAuth.instance.currentUser;` is a Firebase internal user (not to be confused with users that come from the user table), it does not contain any metadata. It is internal Firebase type and it should only indicate you the currently logged in user - by comparing `uid` from the internal user to the `id` of the user from the users table.

In your snipped you try to read metadata from the internal user, it is impossible, you should use `user` from the `users` table that you compared `if (currentUser?.uid != user.id) { user.metadata }`

When you're updating user you need to pass the whole json of the user, get it from the users stream, map to json and paste to the `.update(userJson);` not just `.update({'metadata': activities});`

**Comment by orangeRobot990** [comment]
I noticed that 
var users = FirebaseChatCore.instance.users(); returns all users except the current one, how can i get the currentUser from the firebasechatcore ? I found FirebaseChatCore.instance.firebaseUser but it is equivalent to what i had before which does not have the metadata.
ty

**Comment by demchenkoalex** [comment]
You're right indeed, users do not return the current user https://github.com/flyerhq/flutter_firebase_chat_core/blob/9432c388c702342e771670a0324410b3f1e1db0f/lib/src/firebase_chat_core.dart#L426 

then it is as simple as 

FirebaseFirestore.instance.collection(users).doc(firebaseUser.uid)
