### ISSUE TITLE
My custom auth service

### ISSUE THREAD

**Issue by foxdev-flutter** [flyerhq/flutter_firebase_chat_core#60]
I have a question concerning custom service for auth. Such as, I am want to use my server logic with auth instead of Firebase Auth. I can is it make or not?

I see that this package uses Firebase auth rules, so I want to implement my logic for user auth. And I want that how developers to have a possibility to select between Firebase Auth and them auth logic

**Comment by foxdev-flutter** [comment]
I see that this package uses Firebase auth rules, so I want to implement my logic for user auth. And I want that how developers to have a possibility to select between Firebase Auth and them auth logic

**Comment by demchenkoalex** [comment]
Hey @foxdev-flutter I actually never tried it, but as specified in the docs, Firebase Auth has a method that accepts JWT token, so you theoretically could authenticate user with your own solution and then pass the token to the Firebase Auth. This is essential, cause we need a user ID from the Firebase Auth which will allow for everything else to work. Firebase docs mention JWT tokens, but maybe other types would work too. You can also get that user ID from the Firebase and store in your own database of users, and you will have like your users with authentication logic and their copies on Firebase (only ID will suffice) and then having both your internal users and Firebase user IDs you can match chats with your internal users.

**Comment by foxdev-flutter** [comment]
Hi @demchenkoalex thanks for the detailed answer, this will be the solution to the problem
