### ISSUE TITLE
Is there a way to align all messages to one side?

### ISSUE THREAD

**Issue by gradycsjohnson** [flyerhq/flutter_firebase_chat_core#61]
While using chat in web mode short messages are spaced very far from each other. That is, your messages appear on the right, and everyone else's on the left.

![image](https://user-images.githubusercontent.com/6729256/152689661-d08f1d17-d6ae-4b6d-b7a2-3f66a1f64178.png)

I know this is normal behaviour for a chat client, but I was wondering if there was a way to align all messages to the left (or right, if that's somehow easier).

Consolation prize: is there a way to always show the author's name on a message, even if it's your own message? I can open a separate issue/question for this if you'd prefer.

Thanks!

**Comment by demchenkoalex** [comment]
https://github.com/flyerhq/flutter_chat_ui/issues/215
