### ISSUE TITLE
why is the firebase web app necessary here 

### ISSUE THREAD

**Issue by istiaque-a** [flyerhq/flutter_firebase_chat_core#63]
In the read-me section, I see:

> 3) Create a web app in [Firebase console](https://console.firebase.google.com/) of your project.

Q1) why do I need a web app while I am developing a Flutter mobile app ? Is this because files will be stored in web ?

>  Create a firebase-config.js file in the example/web folder and put there only js part like this

Q2) Where will I find the `example/web` folder ?

**Comment by demchenkoalex** [comment]
It is not needed, it is just an example for web :) you don't need to do it if you have only a mobile application.
