### ISSUE TITLE
User creation and fetchUser function are incompatible

### ISSUE THREAD

**Issue by AcnoSaga** [flyerhq/flutter_firebase_chat_core#66]
When we create a user using `FirebaseChatCore.instance.createUserInFirestore`, the property `lastSeen` is set as type `int`, but when we use `FirebaseChatCore.instance.createRoom`, an internal method `fetchUser` called expects `lastSeen` to be saved as a timestamp in Firebase.

Can this be fixed? It is causing any calls to `FirebaseChatCore.instance.createRoom` to crash.

**Comment by demchenkoalex** [comment]
Great catch! I set the `lastSeen` inside `createUserInFirestore` to `user.lastSeen` (provided by the user, `int`) but it should be `FieldValue.serverTimestamp()` - basically current time, cause user just created an account, so he was seen just now. Later this value should be updated through cloud functions I guess. Will be released in `v1.5.4`.
