### ISSUE TITLE
UsersPage filter 

### ISSUE THREAD

**Issue by OLIVIER-MULLER** [flyerhq/flutter_firebase_chat_core#68]
Hello,

Thanks for this package...very helpful for beginners !

I'm trying to filter users inside UsersPage.

1) Admin user : need a UsersPage with all users.

2) Users : need a UsersPage with only Admin user

I don't want to connect users with others users.... So users should be able to create a room "only" with admin.

Is there a way to filter the stream ? 

Thanks

**Comment by demchenkoalex** [comment]
Hey! Do you have an indication somewhere that the user is an admin? Maybe you know his ID? or `User` class has a `metadata` field where you can store `isAdmin`. Then, depending on the type of current logged in user, when receiving other users,  you could filter them by ID or `isAdmin`, depending on the needs?

**Comment by OLIVIER-MULLER** [comment]
Hello. Yes I try to use this code : 

If admin user => Display of all users to contact : (snapshot.data)![index]

If not admin user => Display only admin user to contact (avoid all other users) : Display of all users to contact : (snapshot.data)![0];

But admin won't stay at [0] in the array :-) 

I'm trying to target the user with the adminId without success (Not in the chat user collection).

But I think it can be a good fix to target "role" == "Admin" 

Any idea to do that ?

Thanks a lot

**Comment by OLIVIER-MULLER** [comment]
const adminUser = types.User(
                id: '4yVXXXXXXXXXXXXX6v1rF3',
              );

Everything is ok. Thanks for your package

**Comment by demchenkoalex** [comment]
> But I think it can be a good fix to target "role" == "Admin"
>
> Any idea to do that ?

User has metadata field, just set `isAdmin` or whatever flag there (metadata is a map) and it is available on every user, you will be able to check `metadata['isAdmin']` or something like that.
