### ISSUE TITLE
Is it possible not to use cloud firestore as backend?

### ISSUE THREAD

**Issue by cledilsonwisp** [flyerhq/flutter_firebase_chat_core#71]
Hello 👋 

In my project I'm having a conflict with the cloud firestore and socket io, so I can't use the firebase back end, would it be possible to use another one?

**Comment by demchenkoalex** [comment]
Hey!

I mean, this is a Firestore example for the UI library, which is backend agnostic :) You can write whatever backend you want, just don't use this and use the UI library (if you want of course).

Good luck! :)
