### ISSUE TITLE
Pagination for Rooms, and Users stream.

### ISSUE THREAD

**Issue by adar2378** [flyerhq/flutter_firebase_chat_core#76]
## Is your feature request related to a problem?
It would be great to have pagination for Rooms, and Users Stream.

## What solution would you suggest?
https://firebase.flutter.dev/docs/ui/firestore This can be a good start to solve this problem

**Comment by demchenkoalex** [comment]
All paginations are stale, and I don't plan to do them, unless someone from the community does. All the progress can be tracked in #11. It does not mention rooms or users, but it is basically the same as messages, when one of them does have pagination, others are trivial.
