### ISSUE TITLE
 Error: The class 'TextMessage' is abstract and can't be instantiated

### ISSUE THREAD

**Issue by letsdev19** [flyerhq/flutter_firebase_chat_core#79]
I can't build the app because of this bug. 

The classes 'TextMessage', 'FileMessage', 'ImageMessage' and 'CustomMessage' are abstract and cannot be initiated. See attached screenshot, package did not pass static analysis because of the issue.
![Screenshot 2022-06-14 at 06 54 46](https://user-images.githubusercontent.com/47488347/173496564-f535f254-c53f-4e21-aa1d-37a05cbc9436.png)

**Comment by demchenkoalex** [comment]
Updated!
