### ISSUE TITLE
Database structure?

### ISSUE THREAD

**Issue by giorgio79** [flyerhq/flutter_firebase_chat_core#8]
Could you post some screens on how the app stores user messages?
There were some discussions on the best way to do it, like here and other packages:

- https://medium.com/@ngengesenior/database-structure-of-one-to-one-chat-app-with-firebase-93f813184dfe
- https://github.com/nishiths23/flutter-firebase-chat
- https://github.com/nishiths23/flutter-firebase-chat/issues/1

**Comment by demchenkoalex** [comment]
Yeah sure, we use root level collections with sub-collections as described here https://firebase.google.com/docs/firestore/manage-data/structure-data and I believe it is recommended approach, there are a lot of advantages described. On this page if you'll see the `Root-level collections` section, this is exactly how it looks in this lib. Plus we use Firebase UIDs as user ids throughout the app for easy security rules configuration.
