### ISSUE TITLE
Change messages in Stream

### ISSUE THREAD

**Issue by sinapsis793** [flyerhq/flutter_firebase_chat_core#84]
Hello,

How can I change message that got in stream?

For example, I want it to write "qweqwe" on all messages.

<img width="860" alt="Screen Shot 2022-08-07 at 19 00 55" src="https://user-images.githubusercontent.com/76243937/183299899-9420a4b1-dc48-4d21-9a23-731bd46fc3cd.png">

Regards,

**Comment by demchenkoalex** [comment]
Map messages when you receive them in stream before showing them in UI?

**Comment by sinapsis793** [comment]
Yes, I tried it. But it doesn't work. I was not able to map.

**Comment by demchenkoalex** [comment]
but on the screenshot you are changing `repliedMessage`. It is not even used in this library.. or you have something added?

**Comment by sinapsis793** [comment]
It's actually an imaginary thing. I just asked how can I change it. Or is it possible

**Comment by demchenkoalex** [comment]
I did not have that use case, so obviously I did not try that. However, just thinking logically, when you receive a message in the stream, what stops you from modifying it? Not all message types have text, `TextMessage` does for example. So I don't see a problem in checking if the type is `TextMessage` and copyWith it with a new text - according to copyWith from types it is [possible](https://github.com/flyerhq/flutter_chat_types/blob/main/lib/src/messages/text_message.dart#L153).

**Comment by sinapsis793** [comment]
I receive message data in "Chat" ."snapshot.data" has List<message>. But I can not reach "TextMessage" and I can not edit it. I don't understand this method. Can you share a code snippet for example?

<img width="603" alt="Screen Shot 2022-08-08 at 00 23 35" src="https://user-images.githubusercontent.com/76243937/183311434-e718188d-7683-413a-8d4a-de6fb48039ad.png">

**Comment by demchenkoalex** [comment]
Don't have access to the project atm. You have a list of messages, you map through them, you already have that. Inside the map, use a function (e) {} and there you have access to `e` of type Message. Then you do something like (pseudocode)

```dart
if (e is types.ImageMessage) {
  return e.copyWith(text: "qweqwe")
}

return e
```

**Comment by sinapsis793** [comment]
Hello,

Thank you for your answers. Actually, I asked for the encryption issue. It's working. 

When I send the message, I encrypt the message in this method.
<img width="556" alt="Screen Shot 2022-08-08 at 19 52 42" src="https://user-images.githubusercontent.com/76243937/183471375-d3dbbdd6-1ff2-44fd-8349-0ca69ab15986.png">

When I show messages in chat, I decrypt the message with your help. Thank you so much. 
<img width="541" alt="Screen Shot 2022-08-08 at 19 54 10" src="https://user-images.githubusercontent.com/76243937/183471660-a673b090-1888-4eb6-8cbd-6518b0362fdf.png">

In this way, I store values as encrypted. 
<img width="458" alt="Screen Shot 2022-08-08 at 19 55 23" src="https://user-images.githubusercontent.com/76243937/183471932-86b95992-129f-4e25-874a-ae07f8487d0b.png">

I can show messages like that. 
<img width="426" alt="Screen Shot 2022-08-08 at 19 56 01" src="https://user-images.githubusercontent.com/76243937/183472061-522b294e-af52-432b-8cd8-20123703ec7d.png">

Thank you so much :)

**Comment by demchenkoalex** [comment]
Awesome! Cool idea too. Maybe something we will implement in the library itself in the future. Thanks!
