### ISSUE TITLE
Rooms take too much time to get loaded.

### ISSUE THREAD

**Issue by MuhammadMugheesAli** [flyerhq/flutter_firebase_chat_core#85]
# General

## What bug do you experience? 🐞
Rooms take around atleast 15 minutes to appear.For 15 minutes the value of rooms is null.

## How can it be reproduced? 🤔
A few steps to define where does the bug occur.
FirebaseChatCore.instance.rooms()

## What behavior is expected? 💡
The rooms should appear within 1 minute.
<br />

# Extras

## Screenshots or videos 📸
If applicable, add screenshots or videos to help explain your problem.

## Code snippets 📝
If applicable, add code samples to help explain your problem.

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
        body: StreamBuilder<List<types.Room>>(
            stream: FirebaseChatCore.instance.rooms(),
            initialData: const [],
            builder: (context, snapshot) {
              return snapshot.data!.isEmpty  ?  const Center(child: CircularProgressIndicator(),) : ListView.separated(
                itemCount: snapshot.data!.length,
                itemBuilder: (ctx, index) {
                  final room = snapshot.data![index];
                  return ListTile(
                  leading: room.imageUrl == 'No Image'
                      ? const CircleAvatar(
                          foregroundImage:
                              AssetImage('assets/images/avatar.png'),
                          radius: 25,
                        )
                      : CachedNetworkImage(
                          imageUrl: room.imageUrl.toString(),
                          imageBuilder: (context, imageProvider) => Container(
                            width: 50.0,
                            height: 50.0,
                            decoration: BoxDecoration(
                              shape: BoxShape.circle,
                              image: DecorationImage(
                                  image: imageProvider, fit: BoxFit.cover),
                            ),
                          ),
                        ),
                  title: Text(room.name.toString(),style: const TextStyle(fontFamily: 'Muli',fontWeight: FontWeight.w500),),
                  subtitle: Text(room.metadata!['About'].toString(),style: const TextStyle(fontFamily: 'Poppins'),),
                  // trailing: Text(room.updatedAt.toString()),
                  onTap: () {
                    Navigator.of(context).pushNamed(ChatScreen.routeName,
                        arguments: room);
                  },
                );
                },
                separatorBuilder: (BuildContext context, int index) {
                  return Divider(thickness: 1,);
                },
              );
            }));
  }
```

<br />

# Environment info

Please specify the flutter, flutter_firebase_chat_core versions.

flutter: 3.0.4 
flutter_firebase_chat_core: ^1.6.3

`flutter doctor -v` output 👇

[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19044.1889], locale en-US)
    • Flutter version 3.0.4 at E:\Flutter\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (6 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Android-SDK
    • Platform android-32, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32328.378
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\Mughees Ali\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.1889]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 104.0.5112.81
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 104.0.1293.54

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

<br />

# Platform

Device (e.g. Android emulator, iOS simulator, Samsung Galaxy S21): Android emulator

OS version (e.g. iOS 14.5, Android 11): Android 12
<br />

# Additional context

<!-- Thank you for making us better 🤝--!>

**Comment by demchenkoalex** [comment]
Hey @MuhammadMugheesAli `rooms` is a simple call to the database (using the Firebase library), and a map to the room type. Map will never take 15 minutes. So your issue is the same as you would create a new project, use Firebase library and read your rooms - you will see 15 minutes. I don't know why this happens tbh, you have a million of rooms, or slow internet, but I can not definitely do anything here.

**Comment by MuhammadMugheesAli** [comment]
Thanks
