### ISSUE TITLE
Firebase version bump

### ISSUE THREAD

**Issue by znromonk** [flyerhq/flutter_firebase_chat_core#88]
The Firebase plugins have been updated. I tried updating it for my app but `flutter_firebase_chat_core` is using these version.
```
  cloud_firestore: ^3.4.0
  firebase_auth: ^3.5.0
  firebase_core: ^1.20.0
```
Can I request a version bump to newer ones?
```
  cloud_firestore: ^4.0.1
  firebase_auth: ^4.0.1
  firebase_core: ^2.0.0
```

**Comment by aintend-com** [comment]
I have the same issue here, As you might know SafetyNet has updated its criteria so all Firebase packages got Major Update. So We have to migrate too.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/77503908/197746966-28c0b6a7-d3cc-4fa5-b01d-74cc2a42d489.png">

But I get the following error:

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/77503908/197747177-621c3e25-71bd-480e-af52-846a22605511.png">

Please update this packages in requirement

**Comment by ah89** [comment]
Same issue here. Any Updates?

**Comment by demchenkoalex** [comment]
Will update everything this weekend

**Comment by demchenkoalex** [comment]
Updated, will be included in the next release very soon.
