### ISSUE TITLE
createRoom does not set imageUrl to other user's imageUrl

### ISSUE THREAD

**Issue by DanielEidlin** [flyerhq/flutter_firebase_chat_core#92]
## What bug do you experience? 🐞
When creating a room using the `createRoom` function the room's `imageUrl` is null instead of being set to the other user's image and name.

## How can it be reproduced? 🤔
Step 1. Create a room using `createRoom`.
Step 2. Get the room using `room(roomId)`.
Step 3. Check the `imageUrl` property, you'll see that it is null.

## What behavior is expected? 💡
According to the documentation:

> Room class will have the name and image URL taken either from provided ones for the group or set to the other person's image URL and name.

[The relevant section in the documentation](https://docs.flyer.chat/flutter/firebase/firebase-usage#rooms)

# Environment info

Please specify the flutter, flutter_firebase_chat_core versions.

flutter: 3.3.2
flutter_firebase_chat_core: 1.6.3

`flutter doctor -v` output 👇

```sh
[√] Flutter (Channel stable, 3.3.2, on Microsoft Windows [Version 10.0.19044.2251], locale en-US)
    • Flutter version 3.3.2 on channel stable at C:\Users\danie\Dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (9 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\danie\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Users\danie\AppData\Local\Programs\Opera\launcher.exe

[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2017 15.9.40)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
    • Visual Studio Build Tools 2017 version 15.9.28307.1705
    • Windows 10 SDK version 10.0.17763.0
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\danie\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19044.2251]
    • Chrome (web)                       • chrome        • web-javascript • unknown
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 106.0.1370.42

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

<br />

# Platform

Device : Android emulator

OS version: Android 11.0

**Comment by demchenkoalex** [comment]
Hey @DanielEidlin if you will set the imageUrl in Firebase, what do you think users will see? :) correct, for both you and the other person in the room you will see the same photo. In reality, you want to see on your device a photo of the other person and on other device a photo of yourself. And this is handled on UI, by checking if the room imageUrl is null :)

**Comment by DanielEidlin** [comment]
Hey Alex, thanks for the response.

I would suggest to clarify that the UI handles this logic in the documentation. Because it is written in the backend section it gives off the impression that the backend handles this logic.

Also is there a way to get the `imageUrl` manually? I'm trying to create a chat preview widget and I would like to display the image as part of the preview.

**Comment by demchenkoalex** [comment]
Obviously, custom backend will handle this, however Firebase is just a database, so.. 🤷 working with what I have.

Don't understand the second question?

**Comment by DanielEidlin** [comment]
I was meaning to ask if there is some way for me to obtain the image url from the room class without using flutter_chat_ui so that I could render the image of that room, but from the answer to my first question I understand that it is impossible.
Thank you anyway.

**Comment by demchenkoalex** [comment]
I think it is being set here https://github.com/flyerhq/flutter_firebase_chat_core/blob/main/lib/src/util.dart#L58 and this is called on every room fetched, and I guess you can just copy the code and modify to your use case (listen to rooms and also see if the room has empty image, check users and set appropriate image). Proper solution is probably use of cloud functions, which I didn't do a part of the package, because it is not a project, but a set of functions. Also use cases are too specific, everyone wants something different. Regarding `flutter_chat_ui`,  I don't think is involved in any way, packages should be unrelated to each other.
