### ISSUE TITLE
Provider state management

### ISSUE THREAD

**Issue by gwbischof** [flyerhq/flutter_firebase_chat_core#95]
Hello!

Would it make sense to add an option, or a branch to do state management with Provider?
Provider is recommended by Flutter.
https://docs.flutter.dev/development/data-and-backend/state-mgmt/simple

Thanks,
Garrett

**Comment by gwbischof** [comment]
I can contribute code if this is a good idea.

**Comment by demchenkoalex** [comment]
A state management for what exactly? :)
