### ISSUE TITLE
Is it possible to edit firebase_chat_core.dart?

### ISSUE THREAD

**Issue by jeffmayn** [flyerhq/flutter_firebase_chat_core#96]
Is it possible to edit the `firebase_chat_core.dart`-file? I specifically need to add an extra where-clause to this stream

```
Stream<List<types.Room>> rooms({bool orderByUpdatedAt = false}) {
    final fu = firebaseUser;

    if (fu == null) return const Stream.empty();

    final collection = orderByUpdatedAt
        ? getFirebaseFirestore()
            .collection(config.roomsCollectionName)
            .where('userIds', arrayContains: fu.uid)
            .orderBy('updatedAt', descending: true)
        : getFirebaseFirestore()
            .collection(config.roomsCollectionName)
            .where('userIds', arrayContains: fu.uid);

    return collection.snapshots().asyncMap(
          (query) => processRoomsQuery(
            fu,
            getFirebaseFirestore(),
            query,
            config.usersCollectionName,
          ),
        );
```

**Comment by gwbischof** [comment]
There are a few ways that you can make this change.
The best way to do it depends on what you want to do.
1. Edit the file directly.
2. Override the FirebaseChatCore class.
3. Make a PR into this repo with the fix.
4. Fork this repo, make the change on your fork, and install from your fork.

**Comment by gwbischof** [comment]
.../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_firebase_chat_core-1.6.3/lib/src/firebase_chat_core.dart
The file is here for me

**Comment by jeffmayn** [comment]
Hi thanks. I did the 2. suggestion and moved the file into my own code. Works fine with this file, however, tried the same for the User-model, it have some generated code `user.g.dart`, and won't work just copying it in. Do you know how to do this file? Would like to add some fields to this model

**Comment by gwbischof** [comment]
I don't see this file.  Do you mean `users.dart` in the example folder?

**Comment by gwbischof** [comment]
You have to move the `user.g.dart` file into your project also.

**Comment by jeffmayn** [comment]
Yeah, I can see why it would be a mess. Well, last solution for adding fields to the user is just to add them as a map to the `metadata`-field. Thanks a lot for your answers:)

**Comment by demchenkoalex** [comment]
Types come from a separate lib https://github.com/flyerhq/flutter_chat_types because I needed this for UI as well. I tried to add `metadata` everywhere so arbitrary fields can be added as needed. Regarding original question - this lib is quite small and straightforward, if some clauses are missing in some functions inside the lib itself, fetch code can be written from scratch, using same database name with all needed filters I guess.
